# Generated by Django 4.2.24 on 2025-09-17 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('coesao', models.DecimalField(decimal_places=2, help_text='Coesão do solo (kPa)', max_digits=5)),
                ('angulo_atrito_interno', models.DecimalField(decimal_places=2, help_text='Ângulo de atrito interno (graus)', max_digits=5)),
                ('peso_especifico', models.DecimalField(decimal_places=2, help_text='Peso específico (kN/m³)', max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Implemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('largura', models.DecimalField(decimal_places=2, help_text='Largura do implemento (m)', max_digits=5)),
                ('profundidade', models.DecimalField(decimal_places=2, help_text='Profundidade de trabalho (m)', max_digits=5)),
                ('angulo_ataque', models.DecimalField(decimal_places=2, help_text='Ângulo de ataque do implemento (graus)', max_digits=5)),
                ('fator_forma_lamina', models.DecimalField(decimal_places=2, help_text='Fator de forma da lâmina', max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('implemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.implemento')),
                ('solo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculos.solo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
