# Generated by Django 4.2.24 on 2025-09-17 04:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implemento',
            name='fator_forma_lamina',
        ),
        migrations.AddField(
            model_name='implemento',
            name='angulo_atrito_implemento',
            field=models.DecimalField(decimal_places=4, default=Decimal('20.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='implemento',
            name='angulo_plano_falha',
            field=models.DecimalField(decimal_places=4, default=Decimal('45.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='solo',
            name='adesao',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='solo',
            name='sobrecarga',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='implemento',
            name='angulo_ataque',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='implemento',
            name='largura',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='implemento',
            name='profundidade',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
