# Generated by Django 4.2.24 on 2025-09-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0002_remove_implemento_fator_forma_lamina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo',
            name='profundidade_critica',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='velocidade_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
