# Generated by Django 4.2.24 on 2025-09-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0003_calculo_profundidade_critica_calculo_velocidade_kmh'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemento',
            name='m_val',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor de m (coeficiente de distância de ruptura)', max_digits=10, null=True),
        ),
    ]
