# Generated by Django 4.2.24 on 2025-09-18 02:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculos', '0004_implemento_m_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo',
            name='eficiencia_tracao_calculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='lastro_ideal_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='patinagem_calculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='calculo',
            name='potencia_necessaria_cv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='implemento',
            name='angulo_clareira',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='implemento',
            name='angulo_varredura',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='implemento',
            name='espacamento',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Espaçamento entre ferramentas (m)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='implemento',
            name='numero_ferramentas',
            field=models.IntegerField(blank=True, help_text='Número de ferramentas para implementos de dente múltiplos', null=True),
        ),
        migrations.AddField(
            model_name='implemento',
            name='raio_disco',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='implemento',
            name='tipo',
            field=models.CharField(choices=[('dente', 'Dente (Tine)'), ('disco', 'Disco (Disc)')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='implemento',
            name='angulo_ataque',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='implemento',
            name='angulo_atrito_implemento',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('20.0000'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='implemento',
            name='angulo_plano_falha',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('45.0000'), max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Trator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('massa_trator', models.DecimalField(decimal_places=2, help_text='Massa total do trator (kg)', max_digits=10)),
                ('potencia_motor', models.DecimalField(decimal_places=2, help_text='Potência nominal do motor (CV)', max_digits=10)),
                ('raio_roda', models.DecimalField(decimal_places=2, help_text='Raio da roda motriz (m)', max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calculo',
            name='trator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculos.trator'),
        ),
    ]
