# Generated by Django 4.2.24 on 2025-09-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0005_calculo_eficiencia_tracao_calculada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trator',
            name='lastro_atual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lastro atual do trator (kg) - opcional', max_digits=10, null=True),
        ),
    ]
