# Generated by Django 4.2.24 on 2026-03-04 07:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0006_trator_lastro_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='indice_cone',
            field=models.DecimalField(decimal_places=2, default=Decimal('800'), help_text='Índice de cone CI (kPa)', max_digits=8),
        ),
        migrations.AddField(
            model_name='trator',
            name='altura_barra_tracao',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Altura da barra de tração (m)', max_digits=5),
        ),
        migrations.AddField(
            model_name='trator',
            name='distancia_entre_eixos',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.500'), help_text='Distância entre eixos (m)', max_digits=5),
        ),
        migrations.AddField(
            model_name='trator',
            name='peso_dianteiro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso no eixo dianteiro (kN)', max_digits=10),
        ),
    ]
